k9s:
  body:
    bgColor: default
  prompt:
    bgColor: default
  info:
    sectionColor: default
  dialog:
    bgColor: default
    labelFgColor: default
    fieldFgColor: default
  frame:
    border:
      fgColor: white
      focusColor: white
    crumbs:
      bgColor: default
    title:
      fgColor: white
      bgColor: default
      highlightColor: yellow
      counterColor: yellow
      filterColor: yellow
    menu:
      fgColor: default
  views:
    charts:
      bgColor: default
    table:
      bgColor: default
      header:
        fgColor: default
        bgColor: default
    xray:
      bgColor: default
    logs:
      bgColor: default
      indicator:
        bgColor: default
        toggleOnColor: default
        toggleOffColor: default
    yaml:
      colonColor: default
      valueColor: default
