[tools]
age = "latest"
"aqua:iffse/pay-respects" = "latest"
atuin = "latest"
biome = "latest"
chezmoi = "2.70"
codex = "latest"
conftest = "latest"
crane = "latest"
fd = "latest"
fzf = "latest"
gemini-cli = "latest"
glab = { version = "latest", provider = "gitlab", exe = "glab" }
go = "1.26"
just = "latest"
k9s = "latest"
kubecolor = "latest"
neovim = "latest"
node = "26"
opencode = "latest"
oras = "latest"
pack = "latest"
python = "3.14"
rg = "latest"
tmux = "latest"
trivy = "latest"
usage = "latest"
zellij = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = ["python"]
# python.uv_venv_auto = true
# experimental = true

[env]
# _.python.venv = { path = "{{env.PWD}}/.venv" }
# _.python.venv = { path = "{{env.PWD}}/.venv", create = false, uv_create_args = ['--seed'] }

